### ISSUE TITLE
Carthage build fails

### ISSUE THREAD

**Issue by iagomr** [JakeLin/SwiftWeather#14]
Hi,

I just tried to build your project with Carthage, but I can't go around the issue that Alamofire fails to build due to dependencies. Would you know what is wrong here?

Thanks in advance,
Tiago

    xyz:~/Developer/Swift Projects/SwiftWeather-master$ carthage build
    *** xcodebuild output can be found in /var/folders/_x/721jc7bj30xfpwf7zn_4sq900000gn/T/carthage-   xcodebuild.UNMFDA.log
    *** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
    ** BUILD FAILED **

    The following build commands failed:
	    Check dependencies
    (1 failure)

**Comment by iagomr** [comment]
Sorry, I've found out that the issue is related to me not having a paid developer account. 

Cheers,
Tiago

**Comment by JakeLin** [comment]
Hi Tiago,

Thanks for your feedback.

Cheers,
Jake

**Comment by IversonZL** [comment]
This project need a  paid developer account?

**Comment by iagomr** [comment]
I believe you need a paid developer account to build Carthage frameworks. It is not related to this project, but to Carthage.

**Comment by IversonZL** [comment]
I don't understand your reply.I build other project is OK,such as ReactiveCocoa,but SwiftyJSON and Alamofire is failed.

**Comment by iagomr** [comment]
As far as I know, if you are using Carthage to build frameworks such as Alamofire and SwiftyJSON, you must have a paid developer account from Apple.

**Comment by liuwin7** [comment]
Which platform you build? iPhone or simulator? If iPhone, maybe you need a certificate from Apple website.

发自我的 iPhone

**Comment by IversonZL** [comment]
Simulator.How to configuration？

**Comment by IversonZL** [comment]
Simulator.How to configure?
