### ISSUE TITLE
build failed ):

### ISSUE THREAD

**Issue by kunggea** [JakeLin/SwiftWeather#15]
![2015-03-20 11 09 26](https://cloud.githubusercontent.com/assets/3320946/6745435/c22ace66-cef1-11e4-8b52-180349f23ff7.png)

Error Domain=com.apple.dt.IDESourceControlErrorDomain Code=-1 "Missing extension: public.vcs.subversion" UserInfo=0x7ff7e3e702e0 {NSLocalizedDescription=Missing extension: public.vcs.subversion}
Object:   <IDESourceControlManager: 0x7ff7e3d84330>
Method:   -loadRepositories
Thread:   <NSThread: 0x7ff7e1435b60>{number = 1, name = main}

**Comment by kunggea** [comment]
How to fix this?

**Comment by JakeLin** [comment]
Thanks for reporting that, like like a Carthage issue with the new version
of Xcode, I am moving house, I will look at it once I have network
connection.

Thanks
Jake

**Comment by luoyibu** [comment]
I have a similar issue, the log is this:
```
127 code/SwiftWeather git:(master) ▶ carthage update
*** Fetching SwiftyJSON
*** Fetching Alamofire
*** Checking out SwiftyJSON at "2.1.3"
*** Checking out Alamofire at "1.1.2"
*** xcodebuild output can be found in /var/folders/nd/jptj1l9x1xl0gmm9db6fghcm0000gn/T/carthage-xcodebuild.ge9u01.log
*** Building scheme "Alamofire" in Alamofire.xcworkspace
*** Building scheme "SwiftyJSON" in SwiftyJSON.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

**Comment by maikie** [comment]
我也遇到了这个问题，怎么解决？

**Comment by JakeLin** [comment]
Hey guys, since Apple changes the complier again. There is an issue of Alamofire. I will keep an eye on it and update the project once we get Alamofire work with Carthage again.

**Comment by kunggea** [comment]
Ahhhh,we must go behind the Apple,,,,
Thanks For Ur pro

**Comment by JakeLin** [comment]
I think Alamofire is OK now, I am looking at SwiftyJSON now.

**Comment by maikie** [comment]
nice

**Comment by liucheng** [comment]
*** Fetching SwiftyJSON
*** Fetching Alamofire
*** Checking out Alamofire at "1.1.2"
*** Checking out SwiftyJSON at "2.1.3"
*** xcodebuild output can be found in /var/folders/ww/cwp872vd4l14zbc060nmtwp00000gn/T/carthage-xcodebuild.0vAgR7.log
*** Building scheme "Alamofire" in Alamofire.xcworkspace
2015-04-11 17:32:30.852 xcodebuild[3165:177328] [MT] DVTAssertions: Warning in /SourceCache/IDEFrameworks/IDEFrameworks-7569/IDEFoundation/SourceControl/Model/IDESourceControlManager.m:423
Details:  Error Domain=com.apple.dt.IDESourceControlErrorDomain Code=-1 "Missing extension: public.vcs.subversion" UserInfo=0x7fc403e8cd50 {NSLocalizedDescription=Missing extension: public.vcs.subversion}
Object:   <IDESourceControlManager: 0x7fc401642280>
Method:   -loadRepositories
Thread:   <NSThread: 0x7fc401436220>{number = 1, name = main}
Please file a bug at http://bugreport.apple.com with this warning message and any useful information you can provide.
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64 /Users/liucheng/Downloads/SwiftWeather-master/Carthage/Checkouts/Alamofire/Source/Alamofire.swift
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)


the same issue as the above one

**Comment by xzjs** [comment]
Failed to discover shared schemes in project Alamofire.xcodeproj—either the project does not have any shared schemes, or xcodebuild never returned

If you believe this to be a project configuration error, please file an issue with the maintainers at https://github.com/Alamofire/Alamofire/issues/new

what should i do?

**Comment by JakeLin** [comment]
Thank you very much for your patient. I have fixed the building issue again. Hooray, yo me if you still have any problem. 

Thanks
Jake

**Comment by wackoj123** [comment]
Problem still seems to exist... 

$ carthage update
*** Fetching Alamofire
*** Fetching SwiftyJSON
*** Checking out Alamofire at "1.2.1"
*** Checking out SwiftyJSON at "2.2.0"
*** xcodebuild output can be found in /var/folders/k4/4w3qn6s12qz7sclyrhjjy3d40000gn/T/carthage-xcodebuild.rSkhJ8.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)

**Comment by zenghaojim33** [comment]
same error as above

**Comment by JakeLin** [comment]
Which version of Xcode are you guys using. I am using Version 6.3.1 (6D1002), it is ok as I tried a moment ago.

➜  SwiftWeather git:(master) ✗ carthage update
*** Fetching Alamofire
*** Fetching SwiftyJSON
*** Checking out SwiftyJSON at "2.2.0"
*** Checking out Alamofire at "1.2.1"
*** xcodebuild output can be found in /var/folders/r9/2nsd0w6d2mn87jkg75njd3md14_q5m/T/carthage-xcodebuild.WKpCkr.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "SwiftyJSON iOS" in SwiftyJSON.xcworkspace
*** Building scheme "SwiftyJSON OSX" in SwiftyJSON.xcworkspace

**Comment by JakeLin** [comment]
Close this one at the moment, please reopen if you still having it in Version 6.3.1 (6D1002)

**Comment by wackoj123** [comment]
Jake - I am using that same version... 6.3.1 6D1002... 

J.

**Comment by JakeLin** [comment]
Can you clone it again and try? I can not replicate it on my Mac.
