### ISSUE TITLE
swift compiler err

### ISSUE THREAD

**Issue by lhlpasser** [JakeLin/SwiftWeather#17]
no such module "Alamofire "

follow you "readme", can't fine "Carthage update"

my Xcode version :6.3.1

**Comment by lhlpasser** [comment]
execute Cartfile , no such command

**Comment by JakeLin** [comment]
To install the carthage tool on your system, please download and run the Carthage.pkg file for the latest release (https://github.com/Carthage/Carthage/releases), then follow the on-screen instructions..

**Comment by lhlpasser** [comment]
the Carthage is installed, but the problem remain .

**Comment by lhlpasser** [comment]
problem resolved ! thx!

**Comment by JakeLin** [comment]
How did you fix this issue?

**Comment by lhlpasser** [comment]
follow you README file:
after the  Carthage was installed, execute "carthage update",but come out some failed message.
retry several times  and  finally got it fixed.

**Comment by JakeLin** [comment]
Maybe I should remove Carthage, it always cause issues.
