### ISSUE TITLE
carthage build faild for segmentation fault 11

### ISSUE THREAD

**Issue by flybikeGx** [JakeLin/SwiftWeather#19]
```
*** Fetching SwiftyJSON
*** Fetching Alamofire
*** Checking out Alamofire at "1.2.2"
*** Checking out SwiftyJSON at "2.2.0"
*** xcodebuild output can be found in /var/folders/fz/rlgkcxdn54gcf9lj6t7jf3gm0000gn/T/carthage-xcodebuild.rCGG7b.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
A shell task failed with exit code 65
Segmentation fault: 11
```

Xcode Version 6.3.2 (6D2105)
carthage version 0.7.3

**Comment by flybikeGx** [comment]
And cartfile about Alamofire changed to be
```
github "Alamofire/Alamofire" >= 1.2
```
otherwise it will stuck in fetch alamofire

**Comment by IversonZL** [comment]
I have same question！
Error log:
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.3'

**Comment by lanrion** [comment]
@IversonZL  Me too, did you fix it ?

**Comment by JakeLin** [comment]
Sorry guys, I am going to remove Carthage.

**Comment by liuwin7** [comment]
Using CocoaPods? @JakeLin

**Comment by JakeLin** [comment]
Will be git submodules.

**Comment by JakeLin** [comment]
Thanks for reporting this issue. I have updated the app to not use Carthage any more. Please checkout the current version. https://github.com/JakeLin/SwiftWeather
