### ISSUE TITLE
Correct Image and Font Scale on different Devices?

### ISSUE THREAD

**Issue by steffimueller** [JakeLin/SwiftWeather#20]
How do you get the correct Image and Font Scale on different Devices?

I made a stackoverflow question here: 
http://stackoverflow.com/questions/30514110/correct-image-and-font-scale-on-different-devices

Thank you for help.

**Comment by JakeLin** [comment]
Sorry for the late reply, I hope it will help. http://stackoverflow.com/questions/30514110/correct-image-and-font-scale-on-different-devices/30608763#30608763

**Comment by JakeLin** [comment]
Close this issue now, working on Xcode 7 and will support Auto Layout and Adaptive Layout.
