### ISSUE TITLE
Building project failed

### ISSUE THREAD

**Issue by bigface** [JakeLin/SwiftWeather#21]
I followed the instruction to build to project. However, in the Carthage/build/ios folder, there is only the alamofire.framework but the swfityJSON is missing.

**Comment by leodie** [comment]
I also have this problem, someone can help?

**Comment by apleschu** [comment]
Adding to it, same problem here.

**Comment by bravecheng** [comment]
same problem

**Comment by ch-hui** [comment]
how to fix it

**Comment by wangqianjun** [comment]
How to fix it!!!!!!!!!

**Comment by vincentqiu** [comment]
How to fix it

**Comment by ch-hui** [comment]
this guys fixed it @vincentqiu @wangqianjun 
https://github.com/SwiftyJSON/SwiftyJSON/pull/244

**Comment by vincentqiu** [comment]
@ch-hui  It work , thankyou

**Comment by JakeLin** [comment]
Thanks for reporting this, I have updated the checkout folder, it should work now.

**Comment by whauff** [comment]
@JakeLin  still not work

**Comment by JakeLin** [comment]
Thanks for reporting this issue. I have updated the app to not use Carthage any more. Please checkout the current version. https://github.com/JakeLin/SwiftWeather
