### ISSUE TITLE
Building project failed lost Alamofire

### ISSUE THREAD

**Issue by cuitengtai** [JakeLin/SwiftWeather#23]
/Users/CTT/Documents/myGitHub/SwiftWeather/SwiftWeatherService/WeatherService.swift:11:8: No such module 'Alamofire'

**Comment by HenryJee** [comment]
Green hand's meeting the same question

**Comment by jiqiuyucool** [comment]
+1

**Comment by JakeLin** [comment]
Thanks for reporting this issue. I have updated the app to not use Carthage any more. Please checkout the current version. https://github.com/JakeLin/SwiftWeather
