### ISSUE TITLE
carthage update failed

### ISSUE THREAD

**Issue by solarcellsky** [JakeLin/SwiftWeather#26]
*** Fetching SwiftyJSON
*** Fetching Alamofire
*** Checking out Alamofire at "1.3.0"
*** Checking out SwiftyJSON at "2.2.0"
*** xcodebuild output can be found in /var/folders/tf/9pwp1f4s0lv1n861vsyg7mph0000gn/T/carthage-xcodebuild.CBhSqT.log
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
Code Sign error: No code signing identities found: No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.4'
A shell task failed with exit code 65

**Comment by carl1990** [comment]
I have encountered this problem

**Comment by timzaak** [comment]
I discard carthage, and use pod to manage the libs instead, remove the dependence in `linked Frameworks and Libraries` and `Embedded Binaries` of `General`. Then I success to run. Good luck !

**Comment by JakeLin** [comment]
Thanks for reporting this issue. I have updated the app to not use Carthage any more. Please checkout the current version. https://github.com/JakeLin/SwiftWeather
