### ISSUE TITLE
can not build in xcode7-beta4 swift2

### ISSUE THREAD

**Issue by nickelchen** [JakeLin/SwiftWeather#27]
hi, I cloned the repo and try to build it in xcode7-beta, and have encounted following build issues.
1. carthage update . error. 
solved.  
1). upgrade carthage to 0.8; 
2). modify Cartfile to
```
github "Alamofire/Alamofire" "swift-2.0"
github "SwiftyJSON/SwiftyJSON" "xcode7"
```
Then in xcode, hit Cmd+B, It compliant several errors.
Swift Compiler Error. 
Ditto Error.
PBXCp Error.
and so on.
then I stucked at this point. anyone helps?

**Comment by nickelchen** [comment]
Solved the issue. It seems that Alamofire swift-2.0 version has changed the api.

**Comment by JakeLin** [comment]
Thanks for reporting this issue. I am working on Xcode 7 version now. Will use iOS 9 only features like `UIStackView`
