### ISSUE TITLE
Error finding location

### ISSUE THREAD

**Issue by wunshine** [JakeLin/SwiftWeather#40]
Error finding location: The operation couldn’t be completed. (kCLErrorDomain error 0.)
I just accepted the location permission message,but nothing happened,throw an error as above..

**Comment by JakeLin** [comment]
Did you put your app key there?

**Comment by wunshine** [comment]
yes, i had put it

**Comment by wunshine** [comment]
I changed info.plist key "Localization native development region" value to "China" , and it worked, but sometimes it would fail to get my location.

**Comment by JakeLin** [comment]
Thanks, I will update the readme file to cover that.

Jake
