### ISSUE TITLE
Error on build

### ISSUE THREAD

**Issue by Scar1** [JakeLin/SwiftWeather#42]
Hi, following the installation instructions the app won't compile:
```
4) Sign up on openweathermap.org/appid to get an appid, then replace your one in OpenWeatherMapService.swift
private let appId = "your appid from openweathermap.org/appid"
```

there is no such thing as private let appId in openWeathermapservice.swift.
Looked through the code and it seems like the app tries to get the appid form the plist file.

 ```

    // get appId from Info.plist
    let filePath = NSBundle.mainBundle().pathForResource("Info", ofType: "plist")!
    let parameters = NSDictionary(contentsOfFile:filePath)
    let appId = ""
    
    components.queryItems = [NSURLQueryItem(name:"lat", value:String(location.coordinate.latitude)),
                             NSURLQueryItem(name:"lon", value:String(location.coordinate.longitude)),
                             NSURLQueryItem(name:"appid", value:String(appId))]
    
    return components.URL
  }
}
```

I've tried inserting the appid I got from openweathermap inside the let appid but it still doesn't work.

error on compile:

cat: /Users/Ben/.access_tokens/openweathermap: No such file or directory
error: Missing OpenWeatherMap access token
error: Get an access token from <http://openweathermap.org/appid>, then create a new file at /Users/Ben/.access_tokens/openweathermap that contains the access token.

**Comment by JakeLin** [comment]
Working on it, thanks

**Comment by JakeLin** [comment]
@Scar1 Can you please pull and follow the updated README.md again? If it is OK, please close the ticket. Thanks to @doedje
