### ISSUE TITLE
City images are not correct

### ISSUE THREAD

**Issue by aybekckaya** [JakeLin/SwiftWeather#51]
In weather result screen , city image is static , and  it is not correct. Maybe it can be used Flickr API

**Comment by JakeLin** [comment]
@aybekckaya it's a good idea to load the city image dynamically. Would you like to have a try to integrate SwiftWeather with Flickr API?

**Comment by pmargom** [comment]
HI, I cloned this repo and I'm already working on this feature.

Regards.

**Comment by JakeLin** [comment]
@pmargom cool, thanks, please let me know if you need anything.

**Comment by pmargom** [comment]
@JakeLin great!! Thanks.

**Comment by aybekckaya** [comment]
@pmargom it is cool , good luck

**Comment by JakeLin** [comment]
@pmargom any update on this? I close this issue for now. Feel free to re-open it if you need, thanks.
