### ISSUE TITLE
Fuzzy about the function in Observable.swift

### ISSUE THREAD

**Issue by nice2m** [JakeLin/SwiftWeather#53]
Thanks for your time!This project is really awesome!I dont understand the whole meaning of funcs in Observerable.swift,Could you please convert it into some Objective-C style funcs?Many thanks

**Comment by vietstone** [comment]
Hi, it's the Observer pattern.
You can find information here:
https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/Properties.html#//apple_ref/doc/uid/TP40014097-CH14-ID262
http://blog.scottlogic.com/2015/02/11/swift-kvo-alternatives.html
Happy coding!

**Comment by JakeLin** [comment]
Thanks, @vietstone . Can we close this issue now @nice2m ?

**Comment by nice2m** [comment]
@vietstone Thanks a lot !   ;-)

**Comment by nice2m** [comment]
@JakeLin much clearer,and Yes you can handle this issue  you like,Thank you for your time.

**Comment by JakeLin** [comment]
Thanks @nice2m
