### ISSUE TITLE
Need the help of the author？

### ISSUE THREAD

**Issue by mrhyh** [JakeLin/SwiftWeather#57]
cat: .access_tokens/openweathermap: No such file or directory
error: Missing OpenWeatherMap access token
error: Get an access token from <http://openweathermap.org/appid>, then create a new file at .access_tokens/openweathermap that contains the access token.

**Comment by JakeLin** [comment]
Please have a look at the step 4 of https://github.com/JakeLin/SwiftWeather#how-to-build, thanks.
