### ISSUE TITLE
any plan to convert to swift 3?

### ISSUE THREAD

**Issue by kywix** [JakeLin/SwiftWeather#60]

**Comment by JakeLin** [comment]
@kywix it is Swift 3, I forgot to upgrade the README.md 😢

**Comment by kevaundray** [comment]
NOOOOOOOOOOOOOOOOOO. I thought that it was swift2 only, so I was perplexed as to why some of the code was written in swift 3, so I just spent all that time converting it to swift 2.3. :)))))))))))))))

**Comment by JakeLin** [comment]
It is done, please see https://github.com/JakeLin/SwiftWeather/releases/tag/V3.0 thanks
