### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by wozuo** [JakeLin/SwiftWeather#9]
Hi Jake Lin,

Great app! Is it possible to help working in this project? I would like to add a forecast feature and a forecast widget in the notification center. May I fork the project and then make a pull request when I implemented the stuff?

kind regards,

Marc

**Comment by JakeLin** [comment]
Hi Marc,

Happy new year, just let you know I have upgrade the project to use Carthage, Alamofire and SwiftyJSON. And I also use framework to share the code between targets. Please have a look if you are interested. 

Thanks
Jake

**Comment by gizmou** [comment]
Hi Jake,

Thanks, happy new year to you too! Ah sounds gread, I'll have a look as soon as I finished all my exams for this semester.

Cheers,
Marc

**Comment by JakeLin** [comment]
Hi Marc,

No rush, all the best for your exams.

Cheers,
Jake
